### ISSUE TITLE
Empty string error

### ISSUE THREAD

**Issue by HannahDeWachter** [statikbe/craft-deepl#11]
Matrix block with following fields:
- Titel (optional)
- Text (optional)
- Entries (required)

When leaving the Text field empty and trying to translate it gives following error:
<img width="1435" alt="DeepL-error" src="https://github.com/statikbe/craft-deepl/assets/55497252/77f19c52-64d1-469c-ad01-437bce032012">

Craft version: 4.8.9
DeepL version: 1.2.0

**Comment by janhenckens** [comment]
We should probably check in https://github.com/statikbe/craft-deepl/blob/develop/src/services/ApiService.php#L24 if we actually have text to translate

**Comment by janhenckens** [comment]
Fixed in 1.4.0
