### ISSUE TITLE
Certain supported fields are not being translated

### ISSUE THREAD

**Issue by janhenckens** [statikbe/craft-deepl#13]
Eg a case on our own website. Block one has plain text fields and those are translated. The second block is a redactor and that doesn't work - while the intro field is a Redactor as well and that **does** get translated.

![Screenshot 20240418-123617-7nBRroMu](https://github.com/statikbe/craft-deepl/assets/755428/b1f582bc-d6fe-4c83-b88a-ed89f8209238)

Needs further investigation.

**Comment by HannahDeWachter** [comment]
The fields are not marked as translatable, therefore are being skipped.
