### ISSUE TITLE
Update `web-auth/webauthn-lib`

### ISSUE THREAD

**Issue by vandres** [statikbe/craft-deepl#17]
Can you please update the dependency `web-auth/webauthn-lib`? There is a moderate security issue.

See https://github.com/craftcms/cms/issues/15377

**Comment by janhenckens** [comment]
Hey @vandres, our plugin doesn't require `web-auth/webauthn-lib` so I'm not sure what we could update.

(it's in the lock file because we require craftcms/cms; but that isn't used when you install the plugin)

**Comment by vandres** [comment]
@janhenckens I am so sorry. This is of course a problem with Craft CMS itself. I got thrown of, because Composer tells me, you are requiring it.
