### ISSUE TITLE
Craft 5, Table field not translatable

### ISSUE THREAD

**Issue by B1nk1e** [statikbe/craft-deepl#20]
I'm using Craft 5.5.3 and using a Table field as a repeater to be able to add USP's. When I want to translate from the default website it wont translate.

I've done the same on a other website with Craft 4 where it does work having the same field settings:

![Screenshot 2024-12-10 at 09 05 17](https://github.com/user-attachments/assets/3ea630dc-ee81-4414-b3bb-1f0434acef68)

**Comment by janhenckens** [comment]
Hey @B1nk1e, the table field isn't supported on the current version - and it wasn't supported in Craft 4 either (the code would have to be in this [file](https://github.com/statikbe/craft-deepl/blob/develop-v4/src/services/fields/fields.php) and it's not there).

Could you check what it's doing on your Craft 4 project? 
In the meantime I'll have a look at adding support :)

**Comment by B1nk1e** [comment]
Hi @janhenckens,

I double checked and see that Craft 4 isn't working either. Can you say if a fix would be coming for this on a short notice?

Kind regards

**Comment by janhenckens** [comment]
I have an initial fix ready, just needs some further testing. Should be able to get a release out by next week I thlink

**Comment by B1nk1e** [comment]
@janhenckens you've got a update for me on this?

**Comment by janhenckens** [comment]
Fix is out in 5.0.1 @B1nk1e! Can you update and try again?
