### ISSUE TITLE
Include Assets in Matrix fields in the translated page

### ISSUE THREAD

**Issue by acmhmedia** [statikbe/craft-deepl#8]
We are a blog with text and images in a blogpost. The images are not inserted into the article within the text field but we insert them separetely in a matrix field. Our previous dev told us that like that we have more possibilities to handle the images.
I installed the translation plugin and everything seems to work fine except one thing. When I am translating the cms entries in the backend (my blogposts) i see the images and everything looks fine however they are not showing in the frontend. Is there a way to implement this?
![Uploading FireShot Capture 057 - ⚙ Best Mouse & Keyboard Settings For Apex Legends [From Pros] - TGG_ - theglobalgaming.com.png…]()

**Comment by janhenckens** [comment]
If you see the images on the translated entry in the Control Panel, I don't think this is an issue with this plugin. 
When creating a fresh entry in the translated site (so not through the DeepL plugin), do those images work or are they broken as well?
